Models/MeetingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MeetingApp.Models
{
    public class MeetingInfo
    {
        public int Id { get; set; }
        public string? Location { get; set; }
        public DateTime Date {get; set; }
        public int NumberOfPeople { get; set; }
    }
}

Models/Repository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MeetingApp.Models
{
    public static class Repository
    {
      private static List<UserInfo> _users = new();
      static Repository()
      {
        _users.Add(new UserInfo() {
            Id=1,
            Name = "Ali",
            Email = "abc@gmail.com",
            Phone = "11111",
            WillAttend = true 
        });
        _users.Add(new UserInfo() {
            Id=2,
            Name = "Veli",
            Email = "abcd@gmail.com",
            Phone = "22222",
            WillAttend = false 
        });
        _users.Add(new UserInfo() {
            Id=3,
            Name = "Ayşe",
            Email = "abcde@gmail.com",
            Phone = "33333",
            WillAttend = true 
        });
      }

      public static List<UserInfo> Users {
        get {
            return _users;
        }
      }

      public static void CreateUser(UserInfo user)
      {
        user.Id = _users.Count+1;
        _users.Add(user);
      }
      public static UserInfo? GetById(int id)
      {
        return _users.FirstOrDefault(user=>user.Id==id);
      }
    }
}

Models/UserInfo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MeetingApp.Models
{
    public class UserInfo
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Ad alanı zorunludur!")]
        public string? Name { get; set; } // null
        [Required(ErrorMessage ="Telefon alanı zorunludur!")]
        public string? Phone { get; set; }
        [Required(ErrorMessage ="Email alanı zorunludur!")]
        [EmailAddress(ErrorMessage ="Hatalı Email!")]
        public string? Email { get; set; }
        [Required(ErrorMessage ="Katılım durumunuzu belirtiniz!")]
        public bool? WillAttend { get; set; } //true, false, null
    }
}

Controllers/HomeController.cs
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            int saat = DateTime.Now.Hour;
            // ViewBag.Selamlama = saat > 12 ? "İyi Günler":"Günaydın";
            // ViewBag.UserName = "Volkan";
            
            ViewData["Selamlama"] = saat > 12 ? "İyi Günler":"Günaydın";;
            int UserCount = Repository.Users.Where(i=>i.WillAttend==true).Count();
            var meetingInfo = new MeetingInfo() {
                Id = 1,
                Location = "İstanbul, Abc Kongre Merkezi",
                Date = new DateTime(2024, 01, 20, 20, 0, 0),
                NumberOfPeople = UserCount
            };

            return View(meetingInfo);
        }
    }
}

Controllers/MeetingController.cs
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers
{
    public class MeetingController : Controller
    {
        // [HttpGet] Default olarak bu metotlar Get metotlarıdır. Bu ibare burada default olarak vardır.
        // [HttpGet] Başına Http Get koyunca ve Form Post Methodu olunca hata verir ama hiç bilgi girmezsek metot post olarak da çalışır. Ancak headre QueryScript alanı boş olacağından bir anlam ifade etmez; çünkü metot parametreleri almalıydı.
        public IActionResult Apply()
        {
            return View();
        }
        // [HttpPost]
        // public IActionResult Apply(string Name, string Phone, string Email, bool WillAttend)
        // {
        //     Console.WriteLine(Name);
        //     Console.WriteLine(Email);
        //     Console.WriteLine(Phone);
        //     Console.WriteLine(WillAttend);
        //     return View();
        // }

        [HttpPost]
        public IActionResult Apply(UserInfo model)
        {
            if(ModelState.IsValid) 
            {
            //burada veritabanı kaydı işlemlerini yapabiliriz.
            Repository.CreateUser(model);
            ViewBag.UserCount = Repository.Users.Where(info=>info.WillAttend == true).Count();
            return View("Thanks", model);
            } else
            {
                return View(model);
            }
        }
            public IActionResult List()
        {
            List<UserInfo> users = Repository.Users;               
            return View(users); 
        }
        //meeting/details/2
        [HttpGet]
        public IActionResult Details(int id)
        {
            return View(Repository.GetById(id));
        }
    }
}

Views/Home/Index.cshtml
@* @using MeetingApp.Models; *@
@model MeetingInfo;
@{
    ViewBag.Title = "Toplantı Başvuru";
    Layout = "_Layout2";
}

<main class="text-center">
@* <h1 class="h4">@ViewBag.Selamlama, @ViewBag.UserName</h1> *@
<h1 class="h4">@ViewData["Selamlama"]</h1>
<p>Toplantı Katılım Durumunuzu Bildiriniz.</p>
<div class="card my-2">
    <ul class="list-group list-group-flush">
        <li class="list-group-item">@Model.Location</li>
        <li class="list-group-item">@Model.Date.ToString("dd/MM/yyyy HH:mm:ss") tarihinde gerçekleşecek</li>
        <li class="list-group-item">@Model.NumberOfPeople Katılımcı</li>
    </ul>
</div>
<a class="btn btn-sm btn-outline-primary" asp-controller="Meeting" asp-action="Apply">Başvuru Yap</a>
</main>

Views/Meeting/Apply.cshtml
@model UserInfo
@{
    ViewBag.Title = "Toplantı Formu";
}
<h1 class="h4 text-center">Toplantı Katılım Formu</h1>
@* form action default olarak tıklandığında get metodu olarak çalışır. Buton vasıtasıyla gerçekleşir. method=post olarak değiştirdik hiç yazılmasaydı get anlamına gelirdi. Post olarak butona tıklayınca çalışmadı. Çünkü mevcut MeetingControllerda post metodu yok. Forum action yazmazsak aynı metot kullanılır (default: action="/Meeting/Apply"). Biz farklı bir url ve metot yazarak başka metodu aktive etmeliyiz.*@
<form method="post" action="/Meeting/Apply" novalidate> @*novalidate yazarak form içinde konrol yapmamasını söyledik çümkü model içinde kontrol yaptık*@
    <div asp-validation-summary="All"></div>
    <div class="mb-3">
        @* label for kullanıyorduk.Şimdi model göndereceğiz asp-for yaptık.Modelde veri tipi yazdığı için artık inpput type=text e de ihtiyacımız yok *@
        <label asp-for="Name" class="form-label">Name</label>
        <input asp-for="Name" class="form-control">
        @*input for="Name" class="form-control" type="text" name="Name" id="Name">*@
    </div>

    <div class="mb-3">
        <label asp-for="Phone" class="form-label">Phone</label>
        <input asp-for="Phone" class="form-control">
    </div>

    <div class="mb-3">
        <label asp-for="Email" class="form-label">Email</label>
        <input asp-for="Email" class="form-control">
    </div>
        <div class="mb-3">
        <label asp-for="WillAttend" class="form-label">Attendence</label>
        <select asp-for="WillAttend" class="form-select">
            <option value="">Seçiniz</option>
            <option value="true">Evet Geliyorum</option>
            <option value="false">Hayır Gelmiyorum</option>
        </select>
    </div>
    <button class="btn btn-primary" type="submit">Kaydet</button>
</form>

Views/Meeting/Details.cshtml
@model UserInfo
@{
    ViewBag.Title = "Başvuru Detayı";
}

@{
    var className = @Model.WillAttend == true ? "success":"danger";
    var durum = @Model.WillAttend == true ? "Katılıyor":"Katılmıyor";
}
<main class=text-center>
    <h1 class="h4">
        Başvuru Detayı
    </h1>
    <p class="badge text-bg-@className"><text>@durum</text></p>
    <p>Name: @Model.Name</p>
    <p>Email: @Model.Email</p>
    <p>Phone: @Model.Phone</p>
    <a asp-controller="Meeting" asp-action="List" class="btn btn-outline-@className">Katılımcı Listesi</a>
</main>

Views/Meeting/List.cshtml
@model List<UserInfo>
@{
    ViewBag.Title = "Toplantı Katılım Listesi";
}

<main class="text-center">
    <h1 class="h4">Toplantı Katılım Listesi</h1>
    <table class="table table-bordered">
        <thead>
            <tr>
                <td>Ad</td>
                <td>Katılım Durumu</td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            @{
                int i = 0;
            }
            @foreach (var user in Model)
            {
                if (user.WillAttend == true)
                {
                    i++;
                }
                var durum = user.WillAttend == true ? "Evet" : "Hayır";
                var className = user.WillAttend == true ? "table-success" : "table-danger";
                <tr class="@className">
                    <td>@user.Name</td>
                    <td>@durum</td>
                    <td>
                        <a class="btn btn-sm btn-primary" href="/meeting/details/@user.Id">Detay</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="card">
        <div class="card-body">
            <span>
                Katılımcı Sayısı: @i
            </span>
        </div>
    </div>

</main>

Views/Meeting/Thanks.cshtml
@model UserInfo
@{
    ViewBag.Title = "Başvuru Durumu";
}
<main class="text-center">
<h1 class="h4">Başvuru Durumu</h1>

@if(Model.WillAttend==true) 
{
<p>Teşekkürler, Sayın @Model.Name Toplantıya Sizinle Birlikte @ViewBag.UserCount Kişi Katılıyor.</p>
<a class="btn btn-sm btn-outline-primary" href="/meeting/list">Katılımcıları Listele</a>
} else
{
    <p>Sayın @Model.Name katılmadığınız için üzgünüz.</p>
    <a class="btn btn-sm btn-outline-primary" href="/meeting/apply">Başvuru Formu</a>
}
</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MeetingApp</title>
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="/css/styles.css"/>
</head>

<body>
    <div class="bg-primary text-white p-2 text-center">
        MeetingApp
    </div>
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto">
                <div class="card">
                    <div class="card-body">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MeetingApp</title>
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css"
        crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
    <div class="bg-success text-white p-2 text-center">
        MeetingApp
    </div>
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto text-center">
                <div class="card">
                    <div class="card-body">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>